### ISSUE TITLE
Laser works on full power all the time.

### ISSUE THREAD

**Issue by WDRplnl** [arkypita/LaserGRBL#1008]
Hi.
I've connected my laser to shield&power and it's working only on 100% power after making switch ON on laser.  All on foto.
![hellp](https://user-images.githubusercontent.com/65569374/82259775-65ab7d80-995c-11ea-9f77-7ee4be603e45.png)
Any suggestions to solve that dear PRO's ?

**Comment by StuartB4** [comment]
If you have the yellow/brown PWM wire correctly connected to the Z+ or Z- pin then everything looks as it should.
It does'nt matter which Z pin because they are both connected together on the underside of the shield on the circuit. 

I've had mine come on full power sometimes and then realised the PWM wire just was'nt making a good connection on the Z- pin. 

You could also check on the underside of the shield for a bad connection on the Z pins, and where the yellow and brown wires are joined.

The only other thing I can think is that with some laser driver boards when the PWM signal is 0v you get full power and when it's 5v it's off.  It's opposite to the normal way of doing it. But without knowing the make or supplier of the laser it's hard to tell if that one is like that.

**Comment by Schwarzi07** [comment]
The Laser looks like a Eleksmaker replacement laser, but they all use the same driver so it isn´t possible to find out what laser that is.

**Comment by WDRplnl** [comment]
I'm thinking about way to invert signal. Mosfet PWM switch wont work that way?
![PWMswitch](https://user-images.githubusercontent.com/65569374/82299017-40972900-99b5-11ea-8721-155f4387cf7d.jpg)

**Comment by StuartB4** [comment]
That's good. :+1:
