### ISSUE TITLE
stays on connecting 

### ISSUE THREAD

**Issue by greenghost12362** [arkypita/LaserGRBL#101]
when i click to begin connecting it just stays at connecting and does not go past that

**Comment by arkypita** [comment]
Is your grbl ok? I mean, are you sure that your [installation of grbl library on your arduino](https://github.com/gnea/grbl/wiki/Flashing-Grbl-to-an-Arduino) is ok?

Did you test also with some other streamer, like ones in [this page](https://github.com/gnea/grbl/wiki/Using-Grbl)? It work with them or not? The problem is only with LaserGRBL?

**Comment by StuartB4** [comment]
May be you are trying to connect to the wrong Com Port.
![com port](https://user-images.githubusercontent.com/16980026/30517144-8f587b48-9b4d-11e7-8cb2-9ef87007bbce.jpg)
