### ISSUE TITLE
G-Code from inkscape gcode generator causes crash

### ISSUE THREAD

**Issue by wyzarddoc** [arkypita/LaserGRBL#133]
every time i attempt to load a gcode file generated by jtech gcode generator for inkscape laserGrbl crashes. Seems the 2600 line file is too big for program. 

[Design1_0002.txt](https://github.com/arkypita/LaserGRBL/files/1366486/Design1_0002.txt)

**Comment by StuartB4** [comment]
Same here. I downloaded your file, loaded it in to LaserGrbl and it crashed without even displaying anything.

**Comment by arkypita** [comment]
I usually use jtech gcode generator plugin without problems.
LaserGRBL has no limits on huge file size, and can handle more then 2 million lines program (tested)

However has problem with negative space, because it's math presupposes that the drawing is all in the positive quadrant of the Cartesian plane. Your drawing seem to be all in the lower right quadrant, with positive X and negative Y.

In some cases he succeeds in drawing a piece of the work, but in other cases (as in this) the number send him into crisis.

**Comment by arkypita** [comment]
A fix is already in development roadmap.

**Comment by arkypita** [comment]
try last release. your file look like this.
check size and position... maybe your file is wrong

![image](https://user-images.githubusercontent.com/8782035/31319069-36e5be8c-ac5d-11e7-9df7-e62cb80ae7f0.png)
