### ISSUE TITLE
Hi friend. Please help me

### ISSUE THREAD

**Issue by RomulRS** [arkypita/LaserGRBL#147]
I have a laser engraver made of two dvd roms. When the engraver burns the picture, the outer contour of the drawing turns black and bold, and all lines inside the drawing are gray. What is the problem?
![20171026_065843](https://user-images.githubusercontent.com/33111677/32035160-f5912e28-ba1f-11e7-840c-1df161130f9f.jpg)

**Comment by arkypita** [comment]
It seems that the original image from which you started has a very thin stroke in the inner parts.
It also seem that you have used line2line. Line2Line try to reproduce the original smoothing/gray of the source image.

Additional smoothing/gray can be generated due to scaling (ie if the original image is very big and you want to draw it small, a nice black stroke can be result in a small smooth line).

Try act on brightness/contrast, threshold or use "vectorize +filling option".

**Comment by RomulRS** [comment]
Thank you for your prompt response. This happens with any image. Attached the original image.
![multfilmy--dora-the-explorer--44](https://user-images.githubusercontent.com/33111677/32045602-558328c6-ba49-11e7-9df7-e759fcfb930b.jpg)

**Comment by arkypita** [comment]
I guess that if you use a DVD sled you have a max size of 40x40mm. Look like you use a resolution of about 5line/mm so the image file that LaserGRBL internally produce for engraving is about 200x200px

This is what happens when you scale a big image to a smaller one:

![small](https://user-images.githubusercontent.com/8782035/32046312-023a965a-ba43-11e7-839e-07f0a23f2bed.jpg)

It look like sharp, but if you zoom it you can easly see that the smallest lines are not "pure black stroke" but they are composed of gray pixels

![small-zommed](https://user-images.githubusercontent.com/8782035/32046348-1ccdcf0a-ba43-11e7-9eeb-b91450aa0ffb.jpg)

**Comment by arkypita** [comment]
Look like that your laser doesn't have enough power to reproduce a good grey engraving, so here the cause of your poor result.

Try to use "NearestNeighbour" as scaling - instead of "HQ Bicubic" and prefer "Vectorization!" tool for this kind of images, as "LineToLine" produce better result on pictures.

**Comment by RomulRS** [comment]
I saw in another program for a laser engraver, that you can choose to additionally outline the contour of the site. But there is no this setting.

**Comment by arkypita** [comment]
I tell you 2 times what to do. Maybe you don't read.

**Comment by RomulRS** [comment]
Thanks for your answers, I will check at home.

**Comment by RomulRS** [comment]
The problem was in the high speed of the motors when burning.
