### ISSUE TITLE
Prewiev is striped and in a bad hue sat i mean. moore in screenshot

### ISSUE THREAD

**Issue by Hum77** [arkypita/LaserGRBL#1655]
Hi,
first of all Thank You for SW, is very intuitive and easy to use.
But I have a problem with photo engraving. As You can see on attached screenshot from normal photo converted to graysteps in a prewiev is this:
![image](https://user-images.githubusercontent.com/63316487/141686315-4fcbae09-8af2-4828-ad18-8f902966b83c.png)

In nearly any setting picture looks same or very similar. Other photos do the same.
It is my fault or is it is a bug?
Petr.

**Comment by arkypita** [comment]
It's not your mistake, and it's not a problem. It's just how lasergrbl works.
lasergrbl draws the preview based on the generated gcode. when the image is very dense the lines are many, so the image appears darker and artifacts may appear due to the superimposition (on video) of the lines that will not actually exist on the finished work.

**Comment by Hum77** [comment]
Hi, thank You for explanation, is absolutely correct, by my mistake i leave (and forgot) 50 lines per mm. 
Problem solved. Thank You for help, fast response and resolving my problem,.
