### ISSUE TITLE
Connection Fail

### ISSUE THREAD

**Issue by kmclain78** [arkypita/LaserGRBL#1890]
Tried to connect LaserGRBL to the laser and immediately received a "exception manager" popup stating something went wrong.  This was just after I updated to 4.9.2.0.
Can not reproduce as now I can not even open GRBL without getting the same error and it immediately telling me to abort.
Three screenshots are loaded for your viewing, I realized they are mostly the same so stopped after the 3rd one and aborted the issue.
I am running Windows 10 fully updated, FoxAlien 20W Reizer Engraver, GRBL 4.9.2.0 updated today (8/7/2022)

Thanks for any help that can be given. 

![2022-08-07](https://user-images.githubusercontent.com/110784945/183306545-00f7141c-e3e1-4dad-b936-0b5563c982ed.png)
![2022-08-07 (2)](https://user-images.githubusercontent.com/110784945/183306550-373d124b-5e2a-40c6-b98a-0f770660136b.png)
![2022-08-07 (1)](https://user-images.githubusercontent.com/110784945/183306558-c8d327b1-ba85-4114-93bb-7f3771e94937.png)

**Comment by arkypita** [comment]
Hi, thanks for reporting. It is definitely something related to the changes I made recently for version 4.9.2
I immediately check the code of the procedure in error, and release a correction as soon as possible.

**Comment by arkypita** [comment]
Could you please post me last lines of your "sessionlog" file? You can open this file via menu "?" -> "open session log"

**Comment by arkypita** [comment]
and Please, also grbl configuration from menu "grbl" -> "grbl configuration" can help me a lot

**Comment by kmclain78** [comment]
Let me know if you can read it. I would love to be able to get to the grbl configuration but I'm unable to get past that screen, it forces me to abort and shuts down.
![20220807_151247](https://user-images.githubusercontent.com/110784945/183307370-03cb107b-4dba-451d-95e1-49b6ab8bab9f.jpg)

**Comment by arkypita** [comment]
Luckily I have a foxalien controller to test, I have identified the problem which is specific to how that machine behaves.
it is a non-adherence to the specification, so I will have to try to understand how to manage it.
I need a few minutes.

**Comment by arkypita** [comment]
As a documentation of the problem, the fact is that the machine responds to the $$ command by sending the parameters with their description added in parentheses. This is incorrect, because the machine should just return the parameter value.

This complicates the reading of the data by the program (in this case LaserGRBL) and makes it more difficult to manage the configuration of string parameters, because it is no longer clear to define what is value and what is description.

![image](https://user-images.githubusercontent.com/8782035/183307787-d7d1d7f6-aa5a-414a-a4a3-d8fb925faa75.png)

00011	00015557	tx	$$\n
00012	00015561	rx	\r
00013	00015561	rx	 $0=5 (step pulse, usec)\r
00015	00015586	rx	 $1=25 (step idle delay, msec)\r
00016	00015587	rx	 $2=0 (step port invert mask:00000000)\r
00017	00015588	rx	 $3=2 (dir port invert mask:00000010)\r
00018	00015588	rx	 $4=0 (step enable invert, bool)\r
00019	00015589	rx	 $5=0 (limit pins invert, bool)\r
00020	00015589	rx	 $6=0 (probe pin invert, bool)\r
00021	00015590	rx	 $10=3 (status report mask:00000011)\r
00022	00015591	rx	 $11=0.010 (junction deviation, mm)\r
00023	00015592	rx	 $12=0.002 (arc tolerance, mm)\r
00024	00015595	rx	 $13=0 (report inches, bool)\r
00025	00015597	rx	 $20=0 (soft limits, bool)\r
00026	00015600	rx	 $21=1 (hard limits, bool)\r
00027	00015603	rx	 $22=1 (homing cycle, bool)\r
00028	00015607	rx	 $23=3 (homing dir invert mask:00000011)\r
00029	00015610	rx	 $24=100.000 (homing feed, mm/min)\r
00030	00015613	rx	 $25=2000.000 (homing seek, mm/min)\r
00031	00015619	rx	 $26=250 (homing debounce, msec)\r
00032	00015622	rx	 $27=2.000 (homing pull-off, mm)\r
00033	00015622	rx	 $30=1000 (spindle max rpm)\r
00034	00015625	rx	 $31=0 (spindle min rpm)\r
00035	00015628	rx	 $32=1 (laser mode, bool)\r
00036	00015631	rx	 $100=160.000 (x, step/mm)\r
00037	00015635	rx	 $101=160.000 (y, step/mm)\r
00038	00015637	rx	 $102=160.000 (z, step/mm)\r
00039	00015821	tx	[3F]

**Comment by kmclain78** [comment]
Ok... So how do I fix it if I can't get into the program?

**Comment by arkypita** [comment]
> Ok... So how do I fix it if I can't get into the program?

No, you can't fix.
I have released new version v4.9.3 and now it should work! 

https://github.com/arkypita/LaserGRBL/releases/download/v4.9.3/install.exe

**Comment by kmclain78** [comment]
Unfortunately it did not... I'll check again later, have to find something else to get some things done as I have shows coming up and need my laser working.  Thank you tho!

![1659903121667632754075144926207](https://user-images.githubusercontent.com/110784945/183309376-1f352bad-2022-46bf-a062-ab46c8c5bc88.jpg)
![16599031644416551209313839123707](https://user-images.githubusercontent.com/110784945/183309385-d512c2c5-a479-4b82-80f7-8d4264c6d004.jpg)

**Comment by arkypita** [comment]
I think your is not working because LaserGRBL store in a file the last configuration it has read from the machine, and now that it have read something wrong is stuck.

Please try deleting (or rename) this file: C:\Users\<your user name>\AppData\Roaming\LaserGRBL\LaserGRBL.Settings.bin

**Comment by arkypita** [comment]
Delete when LaserGRBL is not running :-)
Please let me know.

**Comment by kmclain78** [comment]
Yes, that worked for me.  Thank you.

**Comment by MARTIN83-DOT** [comment]
Help several times I try to enter but this page immediately launches me and the only option is to abort and continue What do I do?
![ERROR](https://user-images.githubusercontent.com/121684865/210101197-68bc989c-4f42-4369-81a3-086a803f5cdd.png)

**Comment by EddyMatel** [comment]
> Help several times I try to enter but this page immediately launches me and the only option is to abort and continue What do I do? ![ERROR](https://user-images.githubusercontent.com/121684865/210101197-68bc989c-4f42-4369-81a3-086a803f5cdd.png)

I have the same problem.
