### ISSUE TITLE
Enhancement: Gcode modifiers

### ISSUE THREAD

**Issue by hk89** [arkypita/LaserGRBL#196]
Hi,

I thought that it will be nicer if had some modifications to the gcode I saved from last time. I can load a gcode file and have multiple modifications like scale stretch, rotate, transform/move and array copy done before engraving. Settings can be set in a window same as I load a JPG file. That would be awesome.

Thanks for your time

**Comment by arkypita** [comment]
Hi @hk89 
What you are requesting is not very easy to implement, because GCode is not a file format that could be easly converted without problem. You know... absolute and relative coordinates, G2-G3 coordinate expressed via radius or IJK format etc.

Also it is not in the in the choice of LaserGRBL to became too much complex. My idea for LaserGRBL is to keep it as more simple as possible and adding too much function could disorient the novice person.

However I seen some time ago a good program for gcode called GRBL-Plotter that have some kind of gcode manipulation. It is C# and it is GPL3, so I have a good start point.

I'll add to dev roadmap too :-)
