### ISSUE TITLE
we want turkish language support

### ISSUE THREAD

**Issue by hmikyas** [arkypita/LaserGRBL#231]
119/5000
turkey hello we are using your software and you would appreciate it if we love so much software in the Turkish language support

**Comment by hmikyas** [comment]
if you come to turkey one day I would like to welcome you

**Comment by arkypita** [comment]
I will be proud to give support for turkey user with Turkish language.

Right now I'm working on a big restructuring of the code and of the user interface, so I suspended any translation jobs included new languages support. As soon as LaserGRBL version 3 will be out, I will resume translations job in the various languages, because they really need to be reviewed.

**Comment by hmikyas** [comment]
thanks
