### ISSUE TITLE
Polish language 

### ISSUE THREAD

**Issue by abatinxs** [arkypita/LaserGRBL#232]
Lot of Polish people using LaserGRBL. It will be nice if You introduce a Polish language to LaserGRBL. Thanks.

**Comment by arkypita** [comment]
I will be proud to give support for Polish user with polish language.

Right now I'm working on a big restructuring of the code and of the user interface, so I suspended any translation jobs included new languages support. As soon as LaserGRBL version 3 will be out, I will resume translations job in the various languages, because they really need to be reviewed.

**Comment by abatinxs** [comment]
arkypita very very thanks :) I`ll be waiting for this and waiting for dxf support.

**Comment by my-pilot-life** [comment]
> 
> 
> I will be proud to give support for Polish user with polish language.
> 
> Right now I'm working on a big restructuring of the code and of the user interface, so I suspended any translation jobs included new languages support. As soon as LaserGRBL version 3 will be out, I will resume translations job in the various languages, because they really need to be reviewed.

Helo
I can translate lasergrbl to Polish
