### ISSUE TITLE
laser has shifted image

### ISSUE THREAD

**Issue by Gabone06** [arkypita/LaserGRBL#24]
Can anyone tell me if the laser has shifted image?
the problem is the machine that we tested on two different cnc.
![20170409_104603](https://cloud.githubusercontent.com/assets/27129600/24835728/06ebb6da-1d12-11e7-82ff-66207801eaa5.jpg)
![braine](https://cloud.githubusercontent.com/assets/27129600/24835729/0fa7ed0c-1d12-11e7-98af-3eba395d15e9.jpg)

**Comment by arkypita** [comment]
It seems to have slipped the belt or that there was a mechanical problem (motor hang?) during engraving process.

I don't think it can depend in any way by LaserGRBL, you should observe the machine while running the job and see if something blocks / disturb the movement of the laser.

**Comment by Gabone06** [comment]
I have 2 cnc (1 is made with cd-roms and 1 with nema without belt.) When i make litle things vectorized i don t have problem. The problem appears when i make pictures.

**Comment by mayhem2408** [comment]
@Gabone06 I haven't seen a problem on my CoreXY rig. Do you have a gcode file you can share that you are having a problem with. I can run it on my rig and see what happens.

**Comment by Gabone06** [comment]
look at this error 
![laser grbl error](https://cloud.githubusercontent.com/assets/27129600/25245064/d6207bb4-260b-11e7-9cea-9754d79bc3f9.png)

**Comment by arkypita** [comment]
Is it a repeatable problem? Meaning that it happens in the same place each time you try or only this one time? 

Could you try to check GCode without running motors? Grbl provide this function by [$C command](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Commands#c---check-gcode-mode).


[Grbl documentation](https://github.com/grbl/grbl/wiki/Interfacing-with-Grbl#grbl--help-message) say that ID 25 mean "A G-code word was repeated in the block.". i.e a line with "G1 X10 X5" will run in error 25, 

![image](https://cloud.githubusercontent.com/assets/8782035/25253255/6fed826e-2620-11e7-9fcb-7e641e47d3e5.png)

As you can see with your eyes, LaserGRBL does not produce invalid GCode lines: "G1 X1 Y-1 F2500 S0" is perfectly valid GCode line. This mean that something was happened between pc-usbport-cable-serial chip-arduino and the valid line sent from PC was interpreted as invalid from grbl on arduino, maybe because serial receiver chip confuse Y as X and generate something like G1 X1 X-1 F2500 S0

Causes could be bad shielded or too long cable, poor quality arduino chinese clone, stepper motor or power line disturbs etc etc etc

https://www.shapeoko.com/forum/viewtopic.php?t=4268&p=31945

**Comment by arkypita** [comment]
https://www.shapeoko.com/forum/viewtopic.php?f=3&t=8669

**Comment by mayhem2408** [comment]
@Gabone06 Looks like you might have a communication problem between your PC and your Arduino. The Gcode line where you have a reported error and the surrounding lines are perfectly valid. I'd say you are experiencing corruptions. Are you able to share the Gcode file so I can test it on my machine?
