### ISSUE TITLE
теряет координаты

### ISSUE THREAD

**Issue by Vytelis** [arkypita/LaserGRBL#293]
почему при гравировки фотографии,теряет координаты и курсор уходит за пределы картинки?
![xxx](https://user-images.githubusercontent.com/37207523/37197086-f717ee96-2381-11e8-9278-0b92e45c15f5.jpg)

**Comment by arkypita** [comment]
The usb-serial communication between PC and Arduino does not use any sort of error-correction or error-checking algorithm, so it is possible that command sent from LaserGRBL/PC could be received slightly different from grbl/arduino. This is intrinsic in this communication type and cannot be fixed by software. https://github.com/grbl/grbl/wiki/Known-Bugs#usb-to-serial-transmission-errors

LaserGRBL contains some communication slow-down that help to minimize this problem, but the best correction is to have good quality USB cable, shielded and far away from motor noise, grounded circuit, and powerline decoupling capacitor.

http://lasergrbl.com/faq

**Comment by vovpff** [comment]
@Vytelis попробуй так же уменьшить ускорение и/или фидрейт.

**Comment by Vytelis** [comment]
Уменьшил ускорение и фидрейт,подключил через качественый кабель,то же самое.Сейчас спомощю Lazer GRBL генерирую G-код, его вставляю в GRBL Controller,а с его помощю работает отлично.

**Comment by vovpff** [comment]
@Vytelis версия grbl какая? лазер в режиме шим работает?
В lasergrbl открывай менбю grbl -> настройки. Пробуй разные варианты Streaming mode (хз как по русски)

**Comment by Vytelis** [comment]
С новой версией laser grbl v2.8.40 работает нормально.
