### ISSUE TITLE
Unidirectional engraving produce wrong result

### ISSUE THREAD

**Issue by arkypita** [arkypita/LaserGRBL#295]
I found an issue with vectorize+filling when used with the flag of unidirectional engraving:

![image](https://user-images.githubusercontent.com/8782035/37240391-d8f0ceb4-244a-11e8-8802-94998b80aaf2.png)

The same image with the same parameters, created without unidirectional flag produce correct output:

![image](https://user-images.githubusercontent.com/8782035/37240410-15e0d53a-244b-11e8-8b9b-6a6cfffd3e70.png)

**Comment by Citizen63** [comment]
Firstly, congratulations and thank you for your fine work. It has provided me with a great deal of pleasure and satisfaction over the past while, during which time I have built a diy laser rig. Your software is by far the best I have found. Cheers.

However.......

I agree with your findings that there seems to be a bug in the rendering side of things. I have thought this for a few months now. With the programme configured for unidirectional engraving, the error
 you describe occurs, Not only filled vectors, Line to Line Tracing is also affected. This issue affects all releases since the unidirectional option was introduced, as far as I can ascertain. It's a real pity as I rely heavily on the unidirectional functionality, as the backlash on my DIY rig is unbearable! (Selfish, I know).

Bidirectional:
![image](https://user-images.githubusercontent.com/37461576/37550189-e731383e-2980-11e8-8c75-9d7a92e20391.png)

Unidirectional:
![image](https://user-images.githubusercontent.com/37461576/37550206-494edc88-2981-11e8-9d6d-e58cab3c7540.png)

![image](https://user-images.githubusercontent.com/37461576/37550237-b5664492-2981-11e8-9f75-065e550bfce7.png)

![image](https://user-images.githubusercontent.com/37461576/37550249-efcbb11c-2981-11e8-9545-f4ff86e9c74a.png)

Here's hoping you manage to find time to give this issue some investigation.

Thanks again.

**Comment by arkypita** [comment]
I have already found the cause, but the solution is not so easy to implement.

In a first pass i look for black and with pixel sequences, generating "segments" that are lines of consecutive pixels of the same grey tone with their length (integer, number of consecutive pixels).

In a second pass i transform all that segments in gcode scaling number of pixels to real mm, producing a double number with a fixed precision (3 decimals) and this necessarily introduces a rounding error.

When in bidirectional engraving segments are produced in both direction, and this balance rounding errors. When unidirectional I produce segments only in engraving direction, than I put only one big segment to "go back". The big segment introduce only a small rounding error, while all the small segments introduce a cumulative rounding error.

If I use two decimals the error is huge, with 3 decimals (actual setup) is visible, with 5 decimals it disappear.

Two decimals
![image](https://user-images.githubusercontent.com/8782035/37553933-7134a804-29d1-11e8-8583-5c7b96d5248d.png)

Five decimals
![image](https://user-images.githubusercontent.com/8782035/37553948-c51e80f2-29d1-11e8-834b-695b427602ef.png)

**Comment by Citizen63** [comment]
Thanks for your prompt reply. I found it informative but it makes me think of a few questions.

> I have already found the cause, but the solution is not so easy to implement.

You seem to have implemented the solution for the example you showed above.

1: Is this something I too could do, if so, how?  Please refer me to any relevant tutorials.  I have basic programming skills, just enough to get me this far, but eager to learn.

2: Is there a reason that calculating to five decimals is not the norm? Does doing so adversely affect other aspects of the programme?

3:  Would you consider a  future release that uses the five decimal place method.


Thanks for your time,
Cheers

**Comment by arkypita** [comment]
> You seem to have implemented the solution for the example you showed above.

The solution I implemented is only one line of code that change the gcode output from #.### to #.###
in [GrblFile.cs line 96](https://github.com/arkypita/LaserGRBL/blob/1501dbaa4bde66893144a041ce52fa5d5ddddda3/LaserGRBL/GrblFile.cs#L96)

However, this so simple solution it is not the right one: rising up the number of decimals will increase the number of character to be sent to grbl, with the result of slow down the streaming speed and limit the maximum engraving speed. For someone this could not be a problem, but for others could be a limit.

The best solution is to cumulate the rounding error to a temporary variable and keep it counted for each next step of calculation. I am trying to implement this way.

**Comment by arkypita** [comment]
Something like this:

`			static double errX;
			public string formatnumberX(double number)
			{
				//return number.ToString("#.###", System.Globalization.CultureInfo.InvariantCulture);

				double orig = number + errX;
				double send = Math.Round(orig, 3);
				errX = send - orig;
				return send.ToString(System.Globalization.CultureInfo.InvariantCulture);
			}

			static double errY;
			public string formatnumberY(double number)
			{
				//return number.ToString("#.###", System.Globalization.CultureInfo.InvariantCulture);

				double orig = number + errY;
				double send = Math.Round(orig, 3);
				errY = send - orig;
				return send.ToString(System.Globalization.CultureInfo.InvariantCulture);
			}`

**Comment by arkypita** [comment]
I have released a version that fix this issue: https://github.com/arkypita/LaserGRBL/releases/tag/v2.8.37
@Citizen63 @Dpsspower and any other user that is using unidirectional can test? Also test bidirectional please :-)

**Comment by Citizen63** [comment]
Good morning, thanks again for your time. I will give your latest release good workout tonight when I get home from work.

**Comment by Dpsspower** [comment]
Hi,
To be honest, I never saw this issue because I never engraved something using the outline vectorisation feature. I do all vectorisation using separate picture processing software.
In the line by line mode, this error never occured to me. I used an older version from end of last year until now. Never change a running system. I never had such distortions in line by line mode.
I always use the unidirectional mode. And it does its job great, increasing sharpness of results dramatically! :-)
I checked it using outline vectorisation + fill and yes - the error was there. But never in line by line only mode.
So this seems to have something to do only with the combination of vectored outline + fill, not with simple line by line engraving.

Now I installed the new release and the error seems to be gone on the screen.
I agree that calculating the error "on the fly" is the better way than increasing output resolution of the output code.

The only thing I cannot understand is, why the problem just happened when adding both outline and line by line fill, and not when using line by line only only.

I will do some more tests.
Thank you very much.

**Comment by arkypita** [comment]
The issue is in line2line algorithm I use both for lin2line and vectorized filling, but when you use vectorization+filling it's more obvious because you have a visual reference.

![image](https://user-images.githubusercontent.com/8782035/37599706-a6f411fe-2b85-11e8-8e6a-77685c862bf0.png)

It is also more visible with certain resolution settings, I.e. with 8 line/mm seem the problem disappear, but with 7 line/mm is very strong. 

![image](https://user-images.githubusercontent.com/8782035/37599985-5e5a58a8-2b86-11e8-83ad-e00ceebbdff6.png)

![image](https://user-images.githubusercontent.com/8782035/37599765-c95e275c-2b85-11e8-9bf5-1acad35d3cac.png)

**Comment by arkypita** [comment]
With the last 2.8.37 the problem seem to be minimized, but not really solved:

![image](https://user-images.githubusercontent.com/8782035/37600377-71d6d676-2b87-11e8-80a9-3fe3e6ddee06.png)

![image](https://user-images.githubusercontent.com/8782035/37600438-9a5d288e-2b87-11e8-92e3-e6ace21a54e1.png)

**Comment by arkypita** [comment]
Please test with v2.8.38, should be the final one!
https://github.com/arkypita/LaserGRBL/releases/tag/v2.8.38

**Comment by Citizen63** [comment]
Hi

Awesome.
I didn't get a chance to try 2_8_37 but I'm putting 2_8_38 through a couple of tests.

(20 minutes later).....

I can't break it! 
Pin sharp imaging now. I'm going to get my goggles and fire up the laser. 

I'll get back to you later after I check some results.
Congratulations and thanks.

**Comment by Citizen63** [comment]
Roger
Over and out.

**Comment by Jelmandesign** [comment]
Is it possible in the latest version of Laser GRBL (v6.2.1) to enable and disable bidirectionality?

**Comment by arkypita** [comment]
@Jelmandesign nothing has changed, did you have any evidence that the future does not work?

**Comment by Jelmandesign** [comment]
I have foundation it in 2e window. Thanks for your reaction. I like your
program!

Kind regards,
Jan Laarman

Op za 16 mrt. 2024 12:13 schreef arkypita ***@***.***>:

**Comment by Jelmandesign** [comment]
I have another question.

For Laser cutting I use my CNC 3018 Pro with laser unit.
The nice thing about LaserGRBL is the possibility to make extra buttons
your self with the functions you want added. to them
Now I have created a button with the command Go to Home position
(right/Top) and then to Left/Bottom. In my case it looks like this:
$H
$j=G91 X-274 Y-162 Z-24 F6800
$x
$x

This puts the machine (for me) in the starting position.
Before I can lasering an opject is ofcours needed.
After this has been imported it is necessary to comfirm the 0-position
with: G90 X0 Y0 Z0 (Third icon from left (with globe symbol)).
What I would like is to add this function to my "ZERO-Button".
So my question is what is needed to add to my program, so that the
0-position-command waits until the move to Left/Bottom is abyssed. So that
at one push of my button the machine executes the following command:
1. Home
2. Left/Bottom (+Z position)
3. ??? wait for confirmation ???
4. G92 X0 Y0 Z0

I'm Sorry for my bad English.

Jan Laarman
The Netherlands


Op za 16 mrt 2024 om 12:13 schreef arkypita ***@***.***>:
