### ISSUE TITLE
Arabic language support. 

### ISSUE THREAD

**Issue by iramuhammad** [arkypita/LaserGRBL#330]
I can help with that. 

Thanks for the great effort.

**Comment by arkypita** [comment]
I have a big code and UI refactoring in progress, so I have currently suspended the addition of new feature and languages because they make the merging process more complicated.
I cannot currently preview when this task will be finished so stay tuned for v3 - when it is out i will contact you for arabic, that is very appreciated.

Best Regards, Diego
