### ISSUE TITLE
New Abort Command litte (Issue) Improvement

### ISSUE THREAD

**Issue by Xillius178** [arkypita/LaserGRBL#344]
Hello Arkypita,
First, thank you for the quick implementation of the cancel button!

1.
I would have liked the abort button down right.
as tall as the others,

if it has to go fast, I'll hit another button.

(the bad accuracy with the mouse is probably due to my shaky age)

Emergency stop switches are always built a bit larger ;-)

2.
I would have a small improvement, since I start the fan with M8,
he continues after the abort command.

You could still write an M09 command?

Whether the fan was previously activated by M8 or not, M09 still works.
And stop the fan.

3.
What I noticed
If I want to cancel, the "Do you want to cancel Yes / No" MessageBox appears

always in the middle of the monitor, it would be better if it always appears in the middle of the program window, from Visual Basic I know that this should be possible.

Slowly the program gets really Perfect!

Thanks for all your work!

Best regards,

Xillius

**Comment by arkypita** [comment]
1. Abort button is very functionally different from suspend/resume and deserves to be placed in a different place. No problem if "wrong hit" by mouse, because confirmation notice is shown.

2. Yes, it is already in roadmap #64 

3. Look like standard messagebox [does not support this option](https://stackoverflow.com/questions/1732443/center-messagebox-in-parent-form) in .NET.
