### ISSUE TITLE
S-min Disabled

### ISSUE THREAD

**Issue by Srinath25** [arkypita/LaserGRBL#35]
![screenshot 203](https://cloud.githubusercontent.com/assets/28611580/25925175/a8ccf8d2-3604-11e7-90e1-663b3b917861.png)
I've been using this software for some days now and I notice that I can't change the S-min settings for PMW control of the laser.
I'am sure the option was available previously.

**Comment by Srinath25** [comment]
![screenshot 203](https://cloud.githubusercontent.com/assets/28611580/25925159/8a9de704-3604-11e7-9bb4-1727dbe83e46.png)

**Comment by arkypita** [comment]
You are right, I have removed S-MIN option.
This is because of the speed optimization feature (move fast and skip all parts with zero laser power) that cannot be effective if S-MIN > 0

Do you use S-MIN values different from zero? Why?
Maybe you can obtain same results "darkening" your image using brightness/contrast control.

**Comment by Srinath25** [comment]
Yes I use it, the material I'm working with is white plywood and to get good greyscale picture on, it needs S-MIN about 40, otherwise it won't even make a scratch (50 it starts to engrave).
Also the S-MAX value can't be higher than 120 which is burning the surface.

So without the S-min it would just come out as a black and white picture with no shades.

**Comment by arkypita** [comment]
Yes, I understand what you mean.
I am thinking to a solution to put together speed optimization and variable S-MIN
Meanwhile you can continue using an older version like 2.5.0 that has free control on S-MIN

**Comment by arkypita** [comment]
Fixed in v2.6.5
