### ISSUE TITLE
Parts of image missing.

### ISSUE THREAD

**Issue by StuartB4** [arkypita/LaserGRBL#385]
Just wondered if you know why this happens on some images.
After clicking Create, the image on the burning screen has bits missing.

This shows all the dots ok.
![dots](https://user-images.githubusercontent.com/16980026/41819497-2cd60eba-77b9-11e8-85e0-054887933657.jpg)

This has some missing.
![dots2](https://user-images.githubusercontent.com/16980026/41819502-45684038-77b9-11e8-9c13-7f239f85f0c2.jpg)

**Comment by arkypita** [comment]
The elaboration of the preview is done on a small sized rescaled image to be sure that the computation time for the preview be reasonably low, to make ui controls responsive. The size is about the preview window pixel size.

The elaboration of the final vector image and gcode is done on a different scaled image, using the final output size (in your case 36x36 mm).

Due to the different scaling of the images the effects of vectorize options can act differently. In your case "spot removal" or other alghoritm is removing all the path that became to small to be significant.

**Comment by StuartB4** [comment]
Ok, thanks very much.
