### ISSUE TITLE
Pause between passes

### ISSUE THREAD

**Issue by jranavaya** [arkypita/LaserGRBL#419]
Hi,

Is there a way of pausing between passes? I want the laser to cool down for 5 minutes between passes.

Is it possible?

Thanks!

**Comment by StuartB4** [comment]
Hi jranavaya. 
Almost 2 months since you asked this question, I've only just seen it in the Issues list.
Just wondered if you managed to do it.

When I do it I load the image in and prepare it for burning.
Before burning I use "Save Program" on the File menu.
Save the GCode and then open it with a text editor, Notepad or Notepad++.
At the end of the code the last line is usually G0 X0 Y0.
After that I just add G4 P300
The 300 is time in seconds (300/60=5 minutes)
Then re-save the code and load that back in to LaserGRBL.
Set the number of passes and click burn.
It stops after the first pass and waits 5 minutes with the laser off before continuing with the next pass and so on until it finishes the last pass.
After the last pass it will still wait 5 minutes or whatever P is set to before stopping completely.
