### ISSUE TITLE
3 AXIS CNC ROUTER 

### ISSUE THREAD

**Issue by manisaranbala** [arkypita/LaserGRBL#445]
I used 3 axis cnc router. your software  v 2.8.52 successfully running but one problem z axis  not showing right side  corner and resume from specific line  (z axis )  please  add z axis WCO 
first flower damaged 
https://youtu.be/YjwxG4P5-fM

**Comment by arkypita** [comment]
Dear @manisaranbala 

LaserGRBL is designed for laser engraver, however its robustness in gcode streaming makes it a good solution even for sending file to CNC.

I read your message and watched the video, but I could not figure out what the problem is. I ask you to try to explain better the problem you are talking about.

**Comment by manisaranbala** [comment]
I used resume from specific line that time damaged job one line i send image.  I think your. Software x and y axis resumed program. Not z axis please. Add z axis. Resume safe hight than running .

**Comment by manisaranbala** [comment]
https://drive.google.com/open?id=1bICFkJ65-pLv93NTID5CPF6-KOtBKlD5
![img_20180921_200134](https://user-images.githubusercontent.com/5657183/45889025-05f27d00-bddd-11e8-9375-6c842e76518b.jpg)
![img_20180921_200233](https://user-images.githubusercontent.com/5657183/45889072-23274b80-bddd-11e8-9ced-0159cfda510c.jpg)

**Comment by arkypita** [comment]
Understand.
I'll get a look at this issue.
