### ISSUE TITLE
SVG negative origin values

### ISSUE THREAD

**Issue by JakeBrownPDX** [arkypita/LaserGRBL#462]
Hey Arkypita, I'm excited to kick the tires on the new SVG feature.  I tried throwing some map data at it and I'm getting some negative values for x and y.  Any ideas?  

<img width="619" alt="laser_grbl" src="https://user-images.githubusercontent.com/12238393/46993087-3ec30080-d0c2-11e8-8eb3-d961a2f93296.PNG">

**Comment by StuartB4** [comment]
Hi Jake.
Just wondered if you found out why it was doing it.

**Comment by JakeBrownPDX** [comment]
No idea @StuartB4 .  Issue persists in version 3.  However, I see the new version 3 has centerline tracing which will actually give me what I need.  Nice work @arkypita , I plan on making a donation.

**Comment by StuartB4** [comment]
Ok Jake, thanks for the reply.

**Comment by arkypita** [comment]
hi @JakeBrownPDX 
It also happened to me to load svg and see them in the wrong position.

The cause is that the SVG format provides dozens of variability and often the programs used to generate the files apply their own custom standards. The code I use for reading SVG files (it is not my code) tries to handle all these probabilities, but always runs out of something.

If you provide a very simple sample file (ie. a square rectangle) that show the issue I can try debug the cause.

**Comment by bbloss** [comment]
A tidbit that might help from my very short laser experience - I sometimes create my SVGs in Inkscape.

Inkscape has the concept of a page upon which you draw. You can draw outside the bounds of the page.

When importing my Inkscape-created SVGs into LaserGRBL the location of the drawn portion within my laser-bed are dependent upon their location to the page origin (lower left in my case).
