### ISSUE TITLE
Some lines simply vanish while being exactly the same as other that didn't.

### ISSUE THREAD

**Issue by RFVasco** [arkypita/LaserGRBL#477]
I've been using Autocad to draw images to engrave with LaserGRBL, but when I load those images on the program, sometimes some lines simply vanish without any criterion, considering I only drew one line and the others where copied. Any ideas how to solve this? I've already thickened the lines on autocad, and while it solved a few of the issues, some others appeared.

![s-02](https://user-images.githubusercontent.com/12994655/47717525-c1040680-dc24-11e8-9989-26398725c386.jpg)
 This image works just fine, but when I try to mend 2 images or more in one, some lines that were fine vanish.

![2-5](https://user-images.githubusercontent.com/12994655/47717492-acc00980-dc24-11e8-8ef5-6696d065fd84.jpg)
The line below "Echeveria" doesn't appear on the program using this image.

![placa s-01 a s-06](https://user-images.githubusercontent.com/12994655/47717538-c9f4d800-dc24-11e8-84bb-9777d5dcacd1.jpg)
None of the midle lines appear with this image.

**Comment by StuartB4** [comment]
Have you tried adjusting the Brightness, Contrast and White Clip.
I tried with the image you posted and it seems ok with the settings I used.

![untitled2](https://user-images.githubusercontent.com/16980026/47725093-d6daf100-dc4f-11e8-9209-beec1b24a495.jpg)

![untitled3](https://user-images.githubusercontent.com/16980026/47725107-dc383b80-dc4f-11e8-8c2d-216411ba4641.jpg)

**Comment by RFVasco** [comment]
Believe it or not, I tried everything, but I don't know the numbers exactly. What was bugging me was that sometimes, with the same configs, some lines would just disappear. Appearently those numbers of yours solved and now all images are working just fine. Thanks for the help (:

**Comment by arkypita** [comment]
@RFVasco as you know, LaserGRBL does not directly support dxf file (for now) so, I think you export your draw in raster image format (.png or .jpg) and then import them in LaserGRBL.

What append in LaserGRBL is that regardless of the exported image resolution, the image is streched (downscaled or upscaled) to fit the required "line/mm * size" resolution.

What I mean: if your export is 4606x1654 (as your last picture posted) and you want to engrave it to a 
23x8cm @ 7lines/mm your image is downscaled to 1610x560 px (230*7 x 80*7) because this is the pixel matrix that is plotted by the laser to respect your request of 23x8cm @ 7lines/mm. 

This downscaling procedure will naturally lost some details.

What I see is that your third picture has very thin lines. about 2pixels of width, and both are "not so black" as they should be, so when scaled the "anti aliasing" algorithm will smooth/fade them and if downscaled too much they will be lost.

![image](https://user-images.githubusercontent.com/8782035/47776580-fe36ca00-dcf2-11e8-879e-cdcb2daed7e9.png)

**Comment by arkypita** [comment]
This effect could be compensated by increasing contrast, but I suggest a better way that could help too.

When you export your image you can manually compute the optimal export resolution. According to previous example if you need engraving 23x8cm @ 7lines/mm export the image at 1610x560 so LaserGRBL doesn't need to resize it.
