### ISSUE TITLE
M4 command don't work.

### ISSUE THREAD

**Issue by EpoHub** [arkypita/LaserGRBL#481]
Hi
M4 command don't work. Program always generate code with M3, I open saved gcode and here also M3 instead M4.
Version v3.0.0

**Comment by StuartB4** [comment]
Try this:

![untitled](https://user-images.githubusercontent.com/16980026/47958780-65da6700-dfca-11e8-9146-78d0ed4ea39c.jpg)

After clicking the Write button you can exit Grbl Config.

If you don't have $30, 31 and 32 in the list then you have an old version of GRBL and need to upgrade to version 1.1.

**Comment by StuartB4** [comment]
Thats really strange. 
Does it only do it with SVG files.
I ask because yesterday I posted this to Arkypita in the SVG thread.
https://github.com/arkypita/LaserGRBL/issues/451
Last entry in the thread.
But it's opposite to your problem.
When I change it to M3 it still writes the M4 command in the code.

**Comment by EpoHub** [comment]
> Thats really strange.
> Does it only do it with SVG files.
> I ask because yesterday I posted this to Arkypita in the SVG thread.
> #451
> Last entry in the thread.
> But it's opposite to your problem.
> When I change it to M3 it still writes the M4 command in the code.

Yep you right I vectorize png and program generate code with M4.

**Comment by arkypita** [comment]
Maybe you are both right. SVG to gcode algorithm is something I have copied so not totally under my control/knowledge, I have included it in LaserGRBL but it is not totally well integrated.

Moreover in v3.0.0 i had to restore a previous version of this code because the needs to integrate it with centerline vectorization.

I will verify it asap
Keep in touch from the next version.

**Comment by StuartB4** [comment]
Ok Arkypita.
Thanks very much for the explaination.

**Comment by arkypita** [comment]
fixed

**Comment by StuartB4** [comment]
Wow, that was quick.

**Comment by StuartB4** [comment]
Thanks very much. 
Tested it a few times and it works absolutely fine now.
