### ISSUE TITLE
Connecting with laser after Update to 3.0

### ISSUE THREAD

**Issue by csavaughan** [arkypita/LaserGRBL#483]
I just updated to version 3.0 and now cannot connect laser to program.  Any help with this matter will be helpful.

**Comment by arkypita** [comment]
LaserGRBL has no known issue with connection.
Maybe the problem is with your hardware.

What do you see in your [device manager](https://support.microsoft.com/en-us/help/4026149/windows-open-device-manager)?

You should see something like this:

![image](https://user-images.githubusercontent.com/8782035/47969631-dfca2900-e07a-11e8-9e2e-1158df4229fa.png)
