### ISSUE TITLE
Homing not working with LaserWed4.. but does with UGS and LaserGRBL

### ISSUE THREAD

**Issue by Member32** [arkypita/LaserGRBL#544]
Homing not working with LaserWed4.. but does with UGS and LaserGRBL

This seems to be an odd issue with homing. (LaserWeb.Setup.4.0.996-130 from Nov 19, 2018)
Everything works fine with UGS... but when I try to home with Laserweb4... it does not see it tripped a limit switch... just keeps driving. (GRBL 1.1g in laser mode)
I am using an UNO + CNC shield (ver 3).
All very easy to setup once you go through the process everyone goes through getting away from benbox.. and you get the very initial Arduino/Grbl learning curve out of the way.

As I mentioned it is an open frame machine with 1X stepper and 2Y steppers.. 
I have limit switches installed at both ends of each access. Homing is set to bottom left ($23-3).
Everything works fine with UGS... except you need a separate package to use UGS, which is why LaserWeb is more appealing. 

I have exported Gcode from LaserWeb4 and burn no problem with UGS.
Plus if I press a limit switch it stops what it’s doing.

I will supply whatever is needed.. I just cannot figure out why it keeps driving past homing switches with LaserWeb4... but not UGS... no matter which corner I have it home to.
Is there something I am missing with LaserWeb vs UGS.
Grbl setup is correct, near as I can tell. It‘s is working in UGS. (Plus UGS verbose mode, I can see the limits get triggered when I trigger them)

Current hardware is HP Zbook Win 10

If this does not get answered for a few days that's OK, it’s a holiday :-)

I would not be surprised if this is something simple that I am missing.. I just finished going back over all documentation in the last week on setting up Laserweb4 and understanding a lot more of what I was reading for both Config.h and Configuration Settings. 
Attached are ConfigH and $ settings so you know how Grbl is setup.

Downloaded LaserGRBL this morning and homing works fine there too.

Happy New Year!! 

Dave

[ConfigurationSettingsGrb l11g.txt](https://github.com/arkypita/LaserGRBL/files/2721110/ConfigurationSettingsGrb.l11g.txt)
[configH 1.1g homing.txt](https://github.com/arkypita/LaserGRBL/files/2721114/configH.1.1g.homing.txt)

**Comment by arkypita** [comment]
Homing is triggered by simply sending $H command to the board.

The board will perform homing procedure by itself: homing procedure is not influenced by what kind of software you have on PC.

Check that LaserWeb send $H and not other commands

**Comment by Member32** [comment]
I have no explanation on why this is working today... I have changed absolutely nothing on my setup, did not even restart my computer.
I burned 2 test projects yesterday with UGS... no issues.
This morning I homed and burned a project with laserGRBL took 32min... then saved the GCODE.
Out of curiosity I wanted to see if it would be faster in LaswerWeb4.
Instead of opening the bmp, I loaded the GCODE file from LAserGRBL and manually moved X&Y to the middle of travel to test homing again. (so I had time to kill power before it hit end of travel)
Hit the "Home all" button and then X travel limit switch and travel stopped... my jaw dropped.
Y hit the limit and backed off... X failed cuz I tripped it early, naturally.
I reset everything... just to be sure... hit "Home all" and it homed as it has been with the other programs.
I burned the test project and it was 6min faster than LaserGRBL... only took 26min).

Closing this because there is no way to provide a solution or determine what was going on.
I was going to video issue today... if it comes back I will do that, as I am still puzzled... lol.

The only thing I can think of was that by opening the GCODE I saved from LaserGRBL it cleared something that was stuck in LaserWeb4. Not sure if that is reality, it's just "grasping at straws" on my part. It is however the ONLY thing I did differently today.

Gotta love Technology!

Dave

**Comment by arkypita** [comment]
> I burned the test project and it was 6min faster than LaserGRBL... only took 26min).

The time needed to process a gcode file largely depend of grbl, because speed of stepper totally depend by arduino timing.

Only a few delay can be added by the sender (LaserGRBL, UGS or LW4) because if it did not stream the gcode in a fluid way it can left the grbl serial buffer without any command for few millisecond adding small delays between gcode commands execution.

LaserGRBL claim to be very very fast, it can stream up to 800 line of gcode per second: https://www.youtube.com/watch?v=pK9GnzNFpHM

I don't know performance of others software, but LaserGRBL performance is very near the hardware limit.

To obtain this result LaserGRBL should be properly configured. Streaming Mode "Buffered" and Threading Mode "UltraFast" or "Insane" will give you top performance.

![image](https://user-images.githubusercontent.com/8782035/50709899-a35e7d80-1069-11e9-9053-7328435f71a5.png)

You can test streaming performance settings grbl to "check mode". Just send "$C" command to put grbl in test mode. In test mode the engine does not move, so you can test pure tx-rx performance.

![image](https://user-images.githubusercontent.com/8782035/50710040-21228900-106a-11e9-9e82-c17e89102107.png)
