### ISSUE TITLE
Edges too dark and fill uniform

### ISSUE THREAD

**Issue by Aztaro** [arkypita/LaserGRBL#565]
Recently tried a very large print with tonal differences in some of the areas, anywhere the laser stopped or slowed was dark but when traveling over any area, even one suppose to be as dark as possible, it all came out one burn density, would switching to an M4 instead of M3 solve both problems or just the edge burning? 
![preview to engrave](https://user-images.githubusercontent.com/46740739/51459063-47f8e480-1d25-11e9-906e-f769bbd39226.jpg)
![file_al9000_1-21-19 2_25 am 1](https://user-images.githubusercontent.com/46740739/51459094-5fd06880-1d25-11e9-9570-fe63af0bc0f1.jpg)

**Comment by PoeticJuicetice** [comment]
You're doing a horizontal print so everything that ends in the horizontal direction will burn extra due to your accelerate and decelerate rate.
Have you tried altering your PWM in relation to your accel and decel rates?
I have issues with this because I find that burning wood (especially really grainy stuff) does not burn 1:1 in terms of PWM and speed. EX: Half the speed and half the laser intensity will not equal the same burn as full speed and full intensity.

**Comment by StuartB4** [comment]
For PWM LaserGRBL generates the GCode "S" power levels between 0 and 255.
Thats what gives you the greyscale.
If you are only using laser power set to 3 out of the 255 then you will have a constant power level.
Prepare your image for burning, then click Save Program on the File menu.
When it's saved open it with Notepad and look at the GCode.
It should have different S values between 0 and 255.

**Comment by brakthehun** [comment]
What laser diode are you using?? Diodes 3W+ are very difficult ot get greyscale with.
