### ISSUE TITLE
Build for Linux

### ISSUE THREAD

**Issue by ggallant571** [arkypita/LaserGRBL#571]
When building on Linux with monodevelop I get 3 errors and three warnings. Suspect I am missing something. First is:
	
	public static string TempPath { get => $"{GrblCore.DataPath}\\Autotrace\\"; } 

/home/ggallant/laser/LaserGRBL-master/LaserGRBL/Autotrace/Autotrace.cs(38,38): Error CS1043: Invalid accessor body `=>', expecting `;' or `{' (CS1043) (LaserGRBL)

**Comment by arkypita** [comment]
I have compiled latest version of LaserGRBL with latest version of monodevelop.
There is some work to do to remove a lot of dependences on XML namespace, using of windows API and more, but no issue on ``=>', expecting `;`

The `=>` syntax for property is available since C# 6.0 language definition, so update your mono/monodevelop version.
