### ISSUE TITLE
Rx, Tx, and ft232 converter

### ISSUE THREAD

**Issue by Cipriano23** [arkypita/LaserGRBL#652]
i couldnt find any info related to this so, before buying anything, wanted ask if someone tried it.
its possible to use Rx and Tx pins through a ft232 converter instead of usb jack?

**Comment by m3vuv** [comment]
ive done that to program pmr radios from rs232 to ttl i think it was,if i remember ttl is 5v logic levels and 232 is 9v,i used a max 232cp ic

**Comment by Cipriano23** [comment]
yea, the converter isnt the problem, i just wanna know if i use Rx and Tx, LaserGRBL will detect it and work like it does with the usb connection on arduino.

**Comment by arkypita** [comment]
I think is possible.
When I use esp8266 to connect grbl via telnet i conenct arduino rx-rx to esp bypassing usb, so it should be ok to do the same with an ft232 as soon LaserGRBL can see it as a COM port.

**Comment by Cipriano23** [comment]
okay then, i already bought the converter. as soon as it arrives ill try it and check if it works.

**Comment by David943** [comment]
well, i bought the yp-02 converter instead of the rs232, i checked both datasheet's and they are similar.
after making the connections, lasergrbl doesnt recognise the Arduino.
i see the converter as a COM port but when i connect it, i dont get the msg that grbl is detected.
my connections, 1- rx to tx, 2- tx to rx, 3- 5v, 4- GND
ive used a jumper on converter, 5v with VCC.

![123](https://user-images.githubusercontent.com/50121402/57990042-2c0a1300-7a79-11e9-8987-f16220941cab.png)

any ideas?

**Comment by Cipriano23** [comment]
well, i bought the yp-02 converter instead of the rs232, i checked both datasheet's and they are similar.
after making the connections, lasergrbl doesnt recognise the Arduino.
i see the converter as a COM port but when i connect it, i dont get the msg that grbl is detected.
my connections, 1- rx to tx, 2- tx to rx, 3- 5v, 4- GND
ive used a jumper on converter, 5v with VCC.

![123](https://user-images.githubusercontent.com/50716536/57990139-ee59ba00-7a79-11e9-9bfb-c90bc3cbae26.png)
(this is the msg that doesnt appear)

any ideas?
