### ISSUE TITLE
Auto cooling

### ISSUE THREAD

**Issue by arkypita** [arkypita/LaserGRBL#658]
Can someone test this feature?
https://github.com/arkypita/LaserGRBL/releases/tag/v3.0.15

@m3vuv
@brakthehun

**Comment by m3vuv** [comment]
i would love to try this but i dont fancy producoucing more firewood,its buggy enough as is!!

**Comment by StuartB4** [comment]
Don't have a cooling problem myself because I only have a 2 Watt laser which has been on continuously for 3 to 4 hours at a time, depending on the image.

Just thought  I'd give it a try.
Tried 3 different images with different On - Off time settings.
Seems to work perfectly.
Another good addition to an already brilliant program.

**Comment by brakthehun** [comment]
I will try it tonight!!

**Comment by brakthehun** [comment]
I did a slow greyscale engraving. Turned out well. I'm a little suspicious of some lines,, but It worked well.
I did a vector created from Inkscape and it took 3 minutes and it paused correctly.

I set it to run for 1 minute,, pause for 1 minute and I set up a 55 second run and told it to run 10 times. It never stopped to cool.

I had one problem - I did a raster and it never paused: 
![2019-05-26 02_27_43-Window](https://user-images.githubusercontent.com/16564592/58379850-f32cdb00-7f5d-11e9-9f4c-d253057412ad.png)

**Comment by brakthehun** [comment]
For what I'm doing,, 6 - 24 hour greyscale engravings,, I think it's great!!

**Comment by arkypita** [comment]
> I set it to run for 1 minute,, pause for 1 minute and I set up a 55 second run and told it to run 10 times. It never stopped to cool. 
> I had one problem - I did a raster and it never paused:

It's strange. Cooling cycle are implemented by sending [feed hold and and cycle resume immediate command](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Commands#ascii-realtime-command-descriptions) and independently from what kind of job (vector/raster etc) is done.

I have tried with raster and it work for me. Can you provide more info?

**Comment by arkypita** [comment]
However I have a big doubt.
In old 0.9 or without laser mode the feed hold command does not turn off the laser. So the stop will burn holes where it stops. There is a better command to send for suspend that is compatible with 0.9 and laser?

**Comment by brakthehun** [comment]
Mighty only work with 1.1 with $32=1.
If timing didn't need to be perfect,, you could send:
M5
G4P60
M3
In the stream.


The estimated time is way off with the cooling pause.

**Comment by arkypita** [comment]
@brakthehun What about `0x84 : Safety Door`

**Comment by brakthehun** [comment]
Ok,, so,, My concern is - if you need to walk away,, how do you actually pause it??
If it''s "cooling" from a 0x84,, the only way to get it to resume would be a "resume" (~) command. You hit pause inside the program,, you could cancel the cooling cycle / resume. If you hit the pause button though,, it will already be in a hold state and the program won't know to continue holding.

The program could have a hold type in the auto-cooling menu.
--------------------------------------------
On Sun, 5/26/19, arkypita <notifications@github.com> wrote:

 Subject: Re: [arkypita/LaserGRBL] Auto cooling (#658)
 To: "arkypita/LaserGRBL" <LaserGRBL@noreply.github.com>
 Cc: "Mr. Baltazar" <brak_the_hun@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Sunday, May 26, 2019, 9:18 AM
 
 @brakthehun What
 about 0x84 : Safety Door
 
 —
 You are
 receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by arkypita** [comment]
> Mighty only work with 1.1 with $32=1.
> If timing didn't need to be perfect,, you could send:
> M5
> G4P60
> M3
> In the stream.

This require to exactly know if laser is on or off when I decide to insert the pause sequence, beacuse at the end of the pause I should restore the previous laser state.

**Comment by brakthehun** [comment]
It's annoying when I forget to turn it off. It would be nice to have a live toggle somewhere.
