### ISSUE TITLE
Benbox

### ISSUE THREAD

**Issue by WHAAWHOO** [arkypita/LaserGRBL#713]
How to get rid of benbox. Can I get another controller board like I have on my 3018pro

**Comment by StuartB4** [comment]
You could get one of these. CNC Spindle and Laser controller in one.
https://www.sainsmart.com/collections/cnc/products/3-axis-grbl-usb-driver-controller-board

**Comment by WHAAWHOO** [comment]
What is the difference between the one you listed and this one that I
bought. And what has to be done to make it work properly.  I'm new to this

**Comment by Dpsspower** [comment]
Sorry guys but this is NOT a LaserGRBL issue!

**Comment by WHAAWHOO** [comment]
But if this benbox was so great folks would not be talking laserGRBL on
here, right. I'm trying to fix it one way or another

**Comment by WHAAWHOO** [comment]
> You could get one of these. CNC Spindle and Laser controller in one.
> https://www.sainsmart.com/collections/cnc/products/3-axis-grbl-usb-driver-controller-board

If I get one of these boards what else would I need to do.  Is it as simple as replacing the board and then using the LaserGRBL that I have already.  Im still trying to learn

**Comment by StuartB4** [comment]
You should be able to, depending on the connectors on your stepper motors, power supply voltage (this one takes 12volt supply) and laser connections.
Do you have any images of the machine you want to put it on?

**Comment by WHAAWHOO** [comment]
file:///home/chronos/u-d25ae8eb34ffb42b2760173dba0bc0d709e64b3a/MyFiles/Downloads/50X65cm%202500MW%20DIY%20Desktop%20Laser%20Engraving%20Machine%20Cutter%20Printer%20Carver%20US%20606989577429%20_%20eBay.mhtml

Had rough day at work,machine is in garage, but the link above is the
machine I have except only 2 stepper motor.  Your help is greatly
appreciated. I also have a 3018 pro that has laser and a carving spindle,
all the connections look the same as that

**Comment by StuartB4** [comment]
Cant see the picture, wrong link.
You mean like this one ?
https://www.ebay.co.uk/itm/NO-VAT-50X65cm-2500MW-DIY-Desktop-Laser-Engraving-Machine-Cutter-Printer-Carver/222581499786?epid=17005353505&hash=item33d2e4278a:g:RQAAAOSw1pZdOsGC

**Comment by WHAAWHOO** [comment]
Yes that looks just mine

**Comment by StuartB4** [comment]
Should be ok then, looks like pretty standard connections.

**Comment by WHAAWHOO** [comment]
I received the board today and when I went to connect the laser it would not connect, the board is a two pin connection and my laser is a 3 pin

**Comment by StuartB4** [comment]
**Did you get this board?**

![48624253-de1a3280-e9a3-11e8-873c-ca01d4a49c4d](https://user-images.githubusercontent.com/16980026/65358076-96ca8700-dbf0-11e9-9640-298fa2fa94bc.jpg)

**If you did then you connect the laser like this.
The yellow wire in the picture is the PWM/TTL positive, it may be Blue or White, Usually they are yellow.**

![48844731-92e09500-ed92-11e8-8ac8-449d9d0538b3](https://user-images.githubusercontent.com/16980026/65358113-af3aa180-dbf0-11e9-8dbe-b9a9e9a76975.jpg)


**I asked Sainsmart who make the board and this is the reply.**

> Hi Stuart,

Since the FAN interface was connected to the 12V power supply directly, the positive and negative terminals of the laser module should be connected to the FAN. That is, the red (positive 12 volt) should be connected to the FAN+ port of the control board.

The Black (Negative/Gnd) should be connected to the FAN- and TTL- port because the TTL- and GND are not in the same GND and they should be connected.

If you used the laser port as the power source, the laser module will not work because the laser module needs the continuous power supply to control the laser intensity 

> .

**Comment by WHAAWHOO** [comment]
Yes that is the board, I read somewhere about the same thing you just to
do.  Thanks

**Comment by StuartB4** [comment]
Ok, good luck with it.

**Comment by WHAAWHOO** [comment]
Thanks for all the help, looks like its working now, had to fabricate a
connection without splicing any wires, since I had plenty of  connectors
from led lights and some other projects. Thanks again

**Comment by StuartB4** [comment]
Thats good to know. If you need any help anytime the LaserGRBL facebook page is a good source.
https://www.facebook.com/groups/486886768471991

**Comment by WHAAWHOO** [comment]
Thanks for that info, maybe will there right now, just checked on my test
project and it is doing it mirrored.
Thanks again

**Comment by StuartB4** [comment]
Have a look here:
https://github.com/arkypita/LaserGRBL/issues/725

**Comment by WHAAWHOO** [comment]
Actually on that page now

**Comment by WHAAWHOO** [comment]
Got it I think for some reason in the config file  X and Y got changed to
inverted, just changed to back to 0 and it seems to be working now

**Comment by StuartB4** [comment]
Good news. :+1:
