### ISSUE TITLE
White dotted outlines on image

### ISSUE THREAD

**Issue by clyde5575** [arkypita/LaserGRBL#75]
Down loaded update and now when I edit image for engraving I get white selected areas on photo, must adjust to point of no contrast to eliminate them.  Photo of image and settings are included.  Any suggestions? Thanks

![pg1](https://user-images.githubusercontent.com/29841624/29490350-7787ed9a-84f6-11e7-8589-c3f24f530e43.jpg)
![pg2](https://user-images.githubusercontent.com/29841624/29490349-77873a26-84f6-11e7-8563-aab33ff89fa1.jpg)

**Comment by clyde5575** [comment]
additional image
![pg 2](https://user-images.githubusercontent.com/29841624/29490378-0c08253e-84f7-11e7-8833-8d41c0158ab2.jpg)

**Comment by arkypita** [comment]
Nothing was added in the very last version that can cause this issue.
What you are showing concern to White Clip, added in June.

The feature of white clip allow you to set a white-point threshold that convert to "pure white" any white value from zero to settled white point.

This could be useful with black and white logos, specially downloaded from web, where sometime whites are not RGB 255, 255, 255 but a very light gray like 254, 253, 254 due to jpg compression or low image quality. In this cases white clip eliminate this noise and prevent laser going burning this areas at very low power wasting time.

With pictures, white clip should be left at zero.

Clipping preview will be shown in pink color when click and drag the "white clip" selector, and disappear when released.

**Comment by clyde5575** [comment]
I reinstalled previous version (v2.2.7.2) and recreated exact setup, see
photo pg 3.  As you can see it does not have the white outlines on the
image,so I reloaded v2.2.7.3 and the lines reappeared.  The white clip is
all the way to the left.

**Comment by arkypita** [comment]
Maybe I have not understand the issue you are talking about, sorry.
The screenshot you have sent is the final output preview, not the raster import form preview. True?
I am investigating the issue.

**Comment by arkypita** [comment]
Thanks @clyde5575 for your fast report of the bug/issue
I have found and fixed it in latest v2.7.4 version
