### ISSUE TITLE
How to make Laser on off command as M106 and M107 for 3d printer converted as laser engraver

### ISSUE THREAD

**Issue by logeshraja-jay** [arkypita/LaserGRBL#784]
Hi,

First of all would like to congratulate you on making such a wonderful software. 

I need to know how to operate my laser which runs on code M106 for ON and M107 for OFF with LaserGRBL software as its not showing that option.

Thanks in Advance,
Logesh

**Comment by arkypita** [comment]
Hi
This feature is already in development roadmap https://github.com/arkypita/LaserGRBL/issues/64 as "Customized code for laser on-off".

However it is not as simple as one might think because the use of codes other than the standard M3 / M4 impacts on various factors such as:


- Drawing preview generation. It is now very easy to recognize the on-off laser status, M3 / M4 and M5. A custom code could also be split over several lines or over several different commands (for example pen up - pen down for plotters).

2) Issue detector and the ability to restart the engraving at stop point: when LaserGRBL intercepts a blockage of the engraving process, or of communication with the engraver, it is able to attempt a restart from the last engraved segment (or very close). This includes the ability to reconstruct the state of the machine and restore the status of any "modal" commands. With custom laser on-off commands (that can be non modal) i think that this code could be no-more able to perform this task.

3) Code optimization. When LaserGRBL create its-own gcode from raster it skip all the subsequent Laser on commands, it just use M3 one time and then use S command to turn off (S0) the laser. Custom on/off conflict with this feature.

Generating GCode with M3/M5 follows some conventions that can be applied on these commands, but that is not said can also be applied to other commands.
