### ISSUE TITLE
Compatability with LaserAxe

### ISSUE THREAD

**Issue by Dragonreborn88** [arkypita/LaserGRBL#789]
I have a Laseraxe DIY system and been having issues with their software (suddenly maxing out my CPU and freezing up the system) so I was looking for another potential software to use. Is there a driver or anything needed to connect/configure? I was able to connect the laser and jog it with the toggles but when I attempt to configure there is no information listed

**Comment by StuartB4** [comment]
If you mean configure LaserGRBL, what happens when you click on the Grbl Configuration option in the Grbl menu top left? 
Normally you would configure the grbl settings from there, and also change any settings in the settings menu there.  If the configuration menu settings are empty it's because you have laseraxe firmware and not GRBL.
You change other settings after you have loaded your image in to it.

**Comment by StuartB4** [comment]
Also you have to be connected to see config settings for grbl, if not connected it reads a cached version and which is not editable.

**Comment by brakthehun** [comment]
What do you need to configure??
