### ISSUE TITLE
Unsupported command

### ISSUE THREAD

**Issue by LJg81** [arkypita/LaserGRBL#984]
Hi, I wonder if anyone can advise.

I have several instances of ‘unsupported command’ when I view my Gcode in LaserGRBL.

I will attach a couple of photographs but I am wondering whether it explains some of the - mainly corner - parts of my design that the laser is not cutting (not coming on for).

Thanks in advance for any help

**Comment by LJg81** [comment]
![IMG_9913](https://user-images.githubusercontent.com/63862725/80751352-859c0e00-8b21-11ea-92a2-d121613c9598.jpg)
![IMG_9914](https://user-images.githubusercontent.com/63862725/80751379-90ef3980-8b21-11ea-8490-1a5481018f02.jpg)

Have circled some areas in Red that have failed to cut. Wondering if the two are related. It looks like the unsupported commands seem to include 'G03'

**Comment by arkypita** [comment]
This error is evidently an error generated by grbl, the program that runs on the control board. LaserGRBL simply brings it back to you. You should ask on the grbl support page. Not here.

It would seem caused by the exponential notation 1.2 .... E-12

What program did you use to generate the G-Code?

**Comment by LJg81** [comment]
Thanks @arkypita - I'll post in the grbl page. Completely new laser cutting and hence these acronyms. Wasn't suggesting it was an error in LaserGRBL, just was on the look out for pointers. 

I used Scan2CAD to generate the G-Code.

Thank you, I'll look for the grbl page.
